config/routes.rb
Treebok::Application.routes.draw do
  get "profiles/show"

  as :user do
  	get '/register', to: 'devise/registrations#new', as: :register 
  	get '/login', to: 'devise/sessions#new', as: :login 
  	get '/logout', to: 'devise/sessions#destroy', as: :logout 
  end

  devise_for :users, skip: [:sessions]
  
  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session 
  	post "/login" => 'devise/sessions#create', as: :user_session
  	delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end
   
  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'
  
  get '/:id', to: 'profiles#show', as: 'profile'
  

end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42613155-4', 'treebookapplication.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">

			<div class="navbar-header">
				<a href="#" class="navbar-brand"> Treebook</a>		
			</div>

			<div class="navbar-header">
				<ul class="nav navbar-nav">					
					<li class="active"><%= link_to "All Statuses", feed_path %></li>	
				</ul>

				<ul class="nav navbar-nav navbar-right pull-right">
					<% if user_signed_in? %>
						<li><%= link_to 'Friends', user_friendships_path %></li>
						<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
						<li><%= link_to "Log Out", logout_path %></li>
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</div>

		</div><!-- container -->
	</nav>

	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<%= message %>
			</div>
		<% end %>
		
		<%= yield %>
		<footer>
			<%= render 'layouts/footer' %> <!-- partical to track all pages, this will be added to all pages -->
		</footer>
	</div>
</body>
</html>